export let data = {
  users: [
    {
      id: "1",
      firstName: "Luis",
      lastName: "Landkoer ",
      userId: "31060856",
      email: "angellandkoer3@gmail.comm",
      password: "barca123",
      phone: "04124388656",
      role: "Tecnico",
      status: "Activo",
    },
    {
      id: "2",
      firstName: "Luis",
      lastName: "Santiago",
      userId: "34521325",
      email: "angellandkoer4@gmail.com",
      password: "barca321",
      phone: "04120473791",
      role: "Tecnico",
      status: "Activo",
    },
    {
      id: "3",
      firstName: "Oneida",
      lastName: "Devia",
      userId: "12890124",
      email: "devia2111@hotmail.com",
      password: "luisaantiago18",
      phone: "04247473539",
      role: "Asistente",
      status: "Activo",
    },
  ],
  clients: [
    {
      firstName: "Jose",
      lastName: "Ernesto",
      clientId: "13110125",
      email: "angellandkoer3@gmail.com",
      phone: "04247142020",
      address: "Ferrero Tamayo",
    },
    {
      firstName: "Jose",
      lastName: "Landkoer",
      clientId: "13110125",
      email: "joselandk@gmail.com",
      phone: "0414910314",
      address: "Ferrero Tamayo",
    },
  ],
  repairs: [
    {
      id: "efe2",
      repairId: "1",
      model: "5656",
      clientName: "gff",
      brand: "fg",
      service: "gffgfg",
      technician: "hgghgh",
      price: "779",
      status: "En proceso",
      password: "",
    },
  ],
  payments: [
    {
      id: "1",
      clientName: "Jose Landkoer",
      referenceNumber: "200200",
      amount: "200",
      date: "2024-12-06",
    },
  ],
  suppliers: [
    {
      id: "1",
      supplierName: "Canguro",
      supplierId: "01",
      email: "canguro@gmail.com",
      phone: "0424789722",
      address: "Avenida 2",
    },
  ],
};
